# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gaia Gaudenzi
email: gaiagaudenzi9@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website!
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
logo: "assets/images/gg.png?raw=true" # your photo (or logo) here

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Gaia Gaudenzi"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Hi all! I am PhD student at University of Maryland!"
  links:
    - label: "X"
      icon: "fab fa-x-twitter fa-fw"
      url: "https://x.com/GaudenziGaia/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gaiagaudenzi-lab"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  google_site_verification: l_z4pt5dVBGf0uewwsyGWC-u-BvX-duoqTbLn9RPAcw

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
